
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/database.types';

const SUPABASE_URL = "https://gvcwesaoocwtldnkhtob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y3dlc2Fvb2N3dGxkbmtodG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTE2NTgsImV4cCI6MjA1ODIyNzY1OH0.4rDM4_JFxxvDkR419NE4NrQO2zXW4VVOEZUbuaVQ_nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
  }
});
